### ISSUE TITLE
Manage ToDo Lists

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/To-Do-App#2]
### **Manage TODO Lists**
Be able to create, view, modify and delete TODO lists

- Cost 4 days
### Presentation Layer

- [ ] Button To Create a New List

- [ ] Button To Manage Created List 

- [ ] Button To Delete and Edit Created Lists
### Logic Layer

- [ ] Create TODO List Object & send to DB interface

- [ ] EdIt TODO List Object & send to DB interface

- [ ] Delete TODO List Object & send to DB interface
