### ISSUE TITLE
Create a TODO list

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/To-Do-App#3]
As a person with specific To-Do tasks to complete, I should be able to create my own To-Do lists.

- Cost: 3days

- From: Manage TODO Lists Feature
### Presentation Layer

- [ ] User can enter the name of TODO List

- [ ] Button to Confirm TODO List creation
### Logic Layer

- [ ] set name  of the TODO list

- [ ] add a new TODO list to the default current category of Lists
