### ISSUE TITLE
View TODO List

### ISSUE THREAD

**Issue by pratikpatelx** [pratikpatelx/To-Do-App#6]
### View TODO List
As a human, I should be able to view the TODO List I created
### Presentation Layer

- [ ] Show TODO List Contents

- [ ] To be able to scroll previous/next content in the TODO List
### Logic Layer

- [ ] get TODO list object from the database

- Cost: 2 days
- Part of: #2
